// svelte/src/App.svelte
<script>
	import Input from "./components/Input.svelte";
	import Select from "./components/Select.svelte";

	let name = '';
	let message = '';
	let selectedValue ='';

	function onSubmit() {
		message = `Brawo ${name}! Wybrałeś ${selectedValue} :)`
	}
</script>

<main>
	<h1>Witaj drogi deweloperze!</h1>
	<form on:submit|preventDefault={onSubmit}>
		<Input bind:value={name}/>
		<Select 
			bind:value={selectedValue}
			optionsList={['React', 'Preact', 'Svelte']}
		/>
		<button type="submit">Wyślij</button>
	</form>
	<h2>{message}</h2>
</main>

<style>
	main {
		display: flex;
		font-family: Helvetica, sans-serif;
		flex-direction: column;
		justify-content: center;
		align-items: center;
	}

	h1 {
		font-size: 1.8rem;
	}

	button {
		background-color: #EA650D;
		padding: 13px 24px;
		font-size: 18px;
		color: #fff;
		border: none;
		border-radius: 3px;
		cursor: pointer;
		margin: 0;
	}
</style>

// react/src/App.tsx
import React, { useState, useCallback } from 'react';
import './App.css';
import { Input } from './components/input/Input';
import { Select } from './components/select/Select';

export const App = (): JSX.Element => {
  const [value, setValue] = useState<string>('');
  const [selectedValue, setSelectedValue] = useState<string>('');
  const [endMessage, setEndMessage] = useState('');

  const onSubmit = useCallback((e: React.FormEvent<HTMLFormElement>)=> {
    e.preventDefault();
    setEndMessage(`Brawo ${value}! Wybrałeś ${selectedValue} :)`)
  },[selectedValue, value]);
  
  return (
    <div className="container">
      <h1>Witaj drogi deweloperze!</h1>
      <form onSubmit={onSubmit}>
        <Input 
          value={value}
          setValue={setValue}
        />
        <Select 
          selectedValue={selectedValue}
          setSelectedValue={setSelectedValue}
          optionsList={['React', 'Preact', 'Svelte']}
        />
        <button type="submit" className="nn-widget__submit--button">Wyślij</button>
      </form>   
      <h2>{endMessage}</h2>
    </div>
  );
}
